jobs:
  build:
    docker:
      - image: us.gcr.io/fasterci/bazelbuilder:9530886
    parallelism: 1
    steps:
      - checkout
      - run:
          name: apoppo
          environment:
            PGPORT: 5433
          command: |
            nproc
